[project]
name = "plex-ratings-dischook"
version = "0.1.0"
description = "A web app to take Plex webhook requests that contain media rating events and activate a Discord webhook notification."
readme = "README.md"
authors = [
    { name = "notchum", email = "github@chum.mozmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "python-dotenv>=1.2.3",
    "ratelimit>=2.2.1",
    "requests>=2.34.2",
]
